export const ROLES = {
  SUPER_ADMIN: "super_admin",
  ADMIN_EMPRESA: "admin_empresa",
  GERENTE: "gerente",
  RECEPCIONISTA: "recepcionista",
  PROFISSIONAL: "profissional",
  CLIENTE: "cliente",
};

export const PERMISSION_MATRIX = {
  [ROLES.SUPER_ADMIN]: [
    "superadmin.access",
    "dashboard.view",
    "appointments.view",
    "appointments.create",
    "appointments.edit",
    "appointments.delete",
    "clients.view",
    "clients.create",
    "clients.edit",
    "clients.delete",
    "services.view",
    "services.create",
    "services.edit",
    "services.delete",
    "services.manage",
    "professionals.view",
    "professionals.create",
    "professionals.edit",
    "professionals.delete",
    "professionals.manage",
    "sales.view",
    "sales.create",
    "sales.edit",
    "sales.delete",
    "financial.view",
    "financial.create",
    "financial.edit",
    "financial.delete",
    "commissions.view",
    "commissions.create",
    "commissions.edit",
    "reports.view",
    "reports.export",
    "settings.view",
    "settings.edit",
    "settings.manage",
    "profile.view",
    "profile.edit",
    "companies.manage",
    "users.manage",
    "roles.manage",
  ],
  [ROLES.ADMIN_EMPRESA]: [
    "dashboard.view",
    "appointments.view",
    "appointments.create",
    "appointments.edit",
    "appointments.delete",
    "clients.view",
    "clients.create",
    "clients.edit",
    "clients.delete",
    "services.view",
    "services.create",
    "services.edit",
    "services.delete",
    "services.manage",
    "professionals.view",
    "professionals.create",
    "professionals.edit",
    "professionals.delete",
    "professionals.manage",
    "sales.view",
    "sales.create",
    "sales.edit",
    "sales.delete",
    "financial.view",
    "financial.create",
    "financial.edit",
    "financial.delete",
    "commissions.view",
    "commissions.create",
    "commissions.edit",
    "reports.view",
    "reports.export",
    "settings.view",
    "settings.edit",
    "profile.view",
    "profile.edit",
    "users.manage",
  ],
  [ROLES.GERENTE]: [
    "dashboard.view",
    "appointments.view",
    "appointments.create",
    "appointments.edit",
    "appointments.delete",
    "clients.view",
    "clients.create",
    "clients.edit",
    "clients.delete",
    "services.view",
    "services.create",
    "services.edit",
    "professionals.view",
    "professionals.create",
    "professionals.edit",
    "sales.view",
    "sales.create",
    "sales.edit",
    "financial.view",
    "commissions.view",
    "commissions.edit",
    "reports.view",
    "profile.view",
    "profile.edit",
  ],
  [ROLES.RECEPCIONISTA]: [
    "dashboard.view",
    "appointments.view",
    "appointments.create",
    "appointments.edit",
    "clients.view",
    "clients.create",
    "clients.edit",
    "services.view",
    "professionals.view",
    "sales.view",
    "sales.create",
    "profile.view",
    "profile.edit",
  ],
  [ROLES.PROFISSIONAL]: [
    "dashboard.view",
    "appointments.view",
    "appointments.edit",
    "clients.view",
    "services.view",
    "professionals.view",
    "commissions.view",
    "profile.view",
    "profile.edit",
  ],
  [ROLES.CLIENTE]: [
    "appointments.view",
    "appointments.create",
    "profile.view",
    "profile.edit",
  ],
};

export function getPermissionsForRole(roleName) {
  if (!roleName) return [];
  return PERMISSION_MATRIX[roleName] || [];
}

export function hasPermission(roleName, permission) {
  const permissions = getPermissionsForRole(roleName);
  if (permissions.includes("*")) return true;
  const parts = permission.split(".");
  for (let i = parts.length; i > 0; i--) {
    const wildcard = parts.slice(0, i).join(".") + ".*";
    if (permissions.includes(wildcard)) return true;
  }
  return permissions.includes(permission);
}

const permissionsLib = {
  ROLES,
  PERMISSION_MATRIX,
  getPermissionsForRole,
  hasPermission,
};

export default permissionsLib;
